### ISSUE TITLE
Code Lens not showing above 'it' line with '.only' feature

### ISSUE THREAD

**Issue by alexneo2003** [90poe/vscode-cy-helper#48]
**Describe the bug**
After install extension i'm not able to use CodeLens with '.only' tag feature

**To Reproduce**
1. Open spec file
3. Inside Developer Tools seen ERR log

**Expected behavior**
 i'm able to use CodeLens with '.only' tag feature

**Environment (please complete the following information):**
- Extension version:                               1.2.1
- VS Code version:                                1.55.0 (user setup)
- OS:                                                     Windows 10:

**Developer Tools Console Output**
```
  ERR not found matches in "": Error: not found matches in ""
    at detectCustomCommand (c:\Users\Alex\.vscode\extensions\shelex.vscode-cy-helper-1.2.1\src\openCustomCommand.js:64:13)
    at CommandDefinitionProvider.provideDefinition (c:\Users\Alex\.vscode\extensions\shelex.vscode-cy-helper-1.2.1\src\providers\CommandDefinitionProvider.js:11:25)
    at c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:158957
    at c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:12046
    at new Promise (<anonymous>)
    at g (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:12018)
    at t.provideDefinition (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:158937)
    at c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:181256
    at Ie._withAdapter (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:179343)
    at Ie.$provideDefinition (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:181232)
    at u._doInvokeHandler (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:12794)
    at u._invokeHandler (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:12478)
    at u._receiveRequest (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:11094)
    at u._receiveOneMessage (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:9931)
    at c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:90:8032
    at _.fire (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
    at E.fire (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15496)
    at c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:30083
    at _.fire (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
    at E.fire (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15496)
    at t._receiveMessage (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20754)
    at c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17640
    at _.fire (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
    at acceptChunk (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12861)
    at c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12209
    at Socket.w (c:\Users\Alex\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:105:13173)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

![image](https://user-images.githubusercontent.com/11705902/113302699-01da3b00-9309-11eb-984f-43fe97f039ee.png)

**Comment by alexneo2003** [comment]
I'm found what is problem 
i'm setting global settings for **editor.codeLens: false**

![image](https://user-images.githubusercontent.com/11705902/113345421-17685880-933b-11eb-8d31-6a8272aea9dc.png)

after change setting to 'true' extension working fine

![image](https://user-images.githubusercontent.com/11705902/113345596-5696a980-933b-11eb-828c-61ca57caf79e.png)
